export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: string;
}

export const CATEGORIES = [
  { id: "developer", name: "Developer Tools", icon: "💻" },
  { id: "text", name: "Text Tools", icon: "📝" },
  { id: "converter", name: "Converters", icon: "🔄" },
  { id: "generator", name: "Generators", icon: "⚡" },
  { id: "crypto", name: "Crypto & Security", icon: "🔒" },
] as const;

export const tools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    category: "developer",
    icon: "{ }",
  },
  {
    slug: "base64-encode-decode",
    name: "Base64 Encode / Decode",
    description: "Encode text to Base64 or decode Base64 strings instantly.",
    category: "converter",
    icon: "B64",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4) with one click. Bulk generation supported.",
    category: "generator",
    icon: "ID",
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text in paragraphs, sentences, or words.",
    category: "text",
    icon: "Aa",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs in any text.",
    category: "text",
    icon: "#",
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URLs and query strings. Handles special characters.",
    category: "converter",
    icon: "%",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text.",
    category: "crypto",
    icon: "#!",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with customizable length and characters.",
    category: "generator",
    icon: "***",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between HEX, RGB, and HSL formats.",
    category: "developer",
    icon: "HEX",
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write Markdown and preview the rendered HTML output in real time.",
    category: "developer",
    icon: "MD",
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier / Beautifier",
    description: "Minify or beautify CSS code. Remove whitespace or format for readability.",
    category: "developer",
    icon: "CSS",
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight the differences line by line.",
    category: "text",
    icon: "+/-",
  },
  {
    slug: "epoch-converter",
    name: "Epoch / Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa.",
    category: "converter",
    icon: "UTC",
  },
  {
    slug: "json-csv-converter",
    name: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV format and CSV back to JSON.",
    category: "converter",
    icon: "CSV",
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Convert any text into a URL-friendly slug. Clean, lowercase, hyphenated.",
    category: "text",
    icon: "/-/",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against text with real-time highlighting of matches.",
    category: "developer",
    icon: ".*",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens. View header, payload, and expiration.",
    category: "crypto",
    icon: "JWT",
  },
  {
    slug: "html-encoder-decoder",
    name: "HTML Encoder / Decoder",
    description: "Encode special characters to HTML entities or decode them back to text.",
    category: "converter",
    icon: "&lt;",
  },
  {
    slug: "cron-generator",
    name: "Cron Expression Generator",
    description: "Build and understand cron expressions with a visual, interactive editor.",
    category: "developer",
    icon: "0 *",
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between decimal, binary, octal, and hexadecimal.",
    category: "converter",
    icon: "0x",
  },
  {
    slug: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text between uppercase, lowercase, camelCase, snake_case, and more.",
    category: "text",
    icon: "Aa",
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions in octal and symbolic notation.",
    category: "developer",
    icon: "rwx",
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between ISO 8601, Unix timestamps, and human-readable dates.",
    category: "converter",
    icon: "T",
  },
  {
    slug: "backslash-escape",
    name: "Backslash Escape / Unescape",
    description: "Escape or unescape special characters like newlines, tabs, and quotes.",
    category: "converter",
    icon: "\\n",
  },
  {
    slug: "ip-address-info",
    name: "IP Address Analyzer",
    description: "Analyze IPv4/IPv6 addresses: class, scope, binary, and hex representation.",
    category: "developer",
    icon: "IP",
  },
  {
    slug: "line-sorter",
    name: "Line Sorter & Deduplicator",
    description: "Sort lines alphabetically, numerically, or by length. Remove duplicates.",
    category: "text",
    icon: "A↓",
  },
  {
    slug: "json-path-finder",
    name: "JSON Path Finder",
    description: "Extract all paths from a JSON object. Filter and copy JSONPath expressions.",
    category: "developer",
    icon: "$.x",
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios and resize dimensions proportionally.",
    category: "converter",
    icon: "16:9",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with proper indentation and keywords.",
    category: "developer",
    icon: "SQL",
  },
  {
    slug: "placeholder-image",
    name: "Placeholder Image Generator",
    description: "Generate lightweight SVG placeholder images with custom dimensions and colors.",
    category: "generator",
    icon: "IMG",
  },
  {
    slug: "yaml-json-converter",
    name: "YAML ↔ JSON Converter",
    description: "Convert between YAML and JSON formats instantly.",
    category: "converter",
    icon: "YML",
  },
  {
    slug: "unicode-lookup",
    name: "Unicode Character Lookup",
    description: "Inspect characters: code points, HTML entities, CSS escapes, UTF-8 bytes.",
    category: "text",
    icon: "U+",
  },
  {
    slug: "hex-rgb-converter",
    name: "HEX ↔ RGB Converter",
    description: "Convert between HEX, RGB, and HSL color values.",
    category: "converter",
    icon: "RGB",
  },
  {
    slug: "js-minifier",
    name: "JavaScript Minifier",
    description: "Minify JavaScript code by removing comments and whitespace.",
    category: "developer",
    icon: "JS",
  },
  {
    slug: "text-repeater",
    name: "Text Repeater",
    description: "Repeat any text multiple times with custom separators.",
    category: "text",
    icon: "x10",
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown format. Handles headings, lists, links, and more.",
    category: "converter",
    icon: "→MD",
  },
  {
    slug: "byte-counter",
    name: "Byte Counter",
    description: "Count bytes, characters, and code points. Shows UTF-8 and UTF-16 sizes.",
    category: "text",
    icon: "B",
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    description: "Generate random numbers within a custom range with various options.",
    category: "generator",
    icon: "?#",
  },
  {
    slug: "morse-code",
    name: "Morse Code Translator",
    description: "Translate text to Morse code and Morse code back to text.",
    category: "converter",
    icon: "·−",
  },
  {
    slug: "rot13",
    name: "ROT13 / Caesar Cipher",
    description: "Encode/decode text with ROT13, ROT47, or custom Caesar cipher shift.",
    category: "crypto",
    icon: "R13",
  },
  {
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create CSS linear and radial gradients with a visual editor and presets.",
    category: "developer",
    icon: "▓",
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Generate TypeScript interfaces from JSON data automatically.",
    category: "developer",
    icon: "TS",
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary",
    description: "Convert text to binary, hexadecimal, octal, or decimal representation.",
    category: "converter",
    icon: "010",
  },
  {
    slug: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Create Markdown tables with a visual editor and column alignment.",
    category: "text",
    icon: "| |",
  },
  {
    slug: "json-stringify",
    name: "JSON Stringify / Parse",
    description: "Convert between formatted and stringified (escaped) JSON.",
    category: "developer",
    icon: '""',
  },
  {
    slug: "box-shadow-generator",
    name: "CSS Box Shadow Generator",
    description: "Create box shadows with a visual editor. Adjust offset, blur, spread, and color.",
    category: "developer",
    icon: "▪",
  },
  {
    slug: "px-converter",
    name: "PX / REM / EM Converter",
    description: "Convert between px, rem, em, pt, vw, vh, and percent CSS units.",
    category: "converter",
    icon: "px",
  },
  {
    slug: "og-meta-generator",
    name: "Open Graph Generator",
    description: "Generate Open Graph and Twitter Card meta tags for social media previews.",
    category: "developer",
    icon: "OG",
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Parse URLs into protocol, hostname, port, path, query params, and hash.",
    category: "developer",
    icon: "://",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate SVG favicons with emoji, text, or initials. No upload needed.",
    category: "generator",
    icon: "ICO",
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs. Customize colors and download as PNG or SVG.",
    category: "generator",
    icon: "QR",
  },
  {
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    description: "Validate JSON data against a JSON Schema. Check types, required fields, and constraints.",
    category: "developer",
    icon: "{}✓",
  },
  {
    slug: "github-readme-generator",
    name: "GitHub README Generator",
    description: "Create an awesome GitHub profile README with stats, badges, and social links.",
    category: "generator",
    icon: "GH",
  },
  {
    slug: "tailwind-color-generator",
    name: "Tailwind Color Generator",
    description: "Generate Tailwind CSS color palettes (50-950) from any base color.",
    category: "developer",
    icon: "TW",
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Format, beautify, and validate XML data with custom indentation.",
    category: "developer",
    icon: "XML",
  },
  {
    slug: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate subnet details from CIDR notation. Network, broadcast, host range, and netmask.",
    category: "developer",
    icon: "IP/",
  },
  {
    slug: "robots-txt-generator",
    name: "robots.txt Generator",
    description: "Generate robots.txt files with crawl rules, sitemaps, and bot-specific directives.",
    category: "developer",
    icon: "BOT",
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes. Random, analogous, complementary, and triadic schemes.",
    category: "generator",
    icon: "PAL",
  },
  {
    slug: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Complete reference of all HTTP status codes (1xx-5xx) with descriptions and examples.",
    category: "developer",
    icon: "200",
  },
  {
    slug: "regex-cheat-sheet",
    name: "Regex Cheat Sheet",
    description: "Quick reference for regular expressions. Character classes, quantifiers, groups, and common patterns.",
    category: "developer",
    icon: "/./",
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate HTML meta tags for SEO. Title, description, viewport, robots, and canonical tags.",
    category: "developer",
    icon: "TAG",
  },
  {
    slug: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate a free privacy policy for your website. GDPR, cookies, and data collection covered.",
    category: "generator",
    icon: "PP",
  },
  {
    slug: "base64-image-encoder",
    name: "Base64 Image Encoder",
    description: "Convert images to Base64 strings. Supports PNG, JPG, GIF, SVG, and WebP formats.",
    category: "converter",
    icon: "IMG",
  },
  {
    slug: "border-radius-generator",
    name: "CSS Border Radius Generator",
    description: "Create CSS border-radius values with a visual editor. Adjust each corner individually.",
    category: "developer",
    icon: "◜◝",
  },
  {
    slug: "htaccess-generator",
    name: ".htaccess Generator",
    description: "Generate .htaccess rules for redirects, HTTPS, caching, and security headers.",
    category: "developer",
    icon: ".ht",
  },
];
