export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: string;
}

export const CATEGORIES = [
  { id: "developer", name: "Developer Tools", icon: "💻" },
  { id: "text", name: "Text Tools", icon: "📝" },
  { id: "converter", name: "Converters", icon: "🔄" },
  { id: "generator", name: "Generators", icon: "⚡" },
  { id: "crypto", name: "Crypto & Security", icon: "🔒" },
  { id: "media", name: "Image & Media Tools", icon: "🖼️" },
  { id: "calculator", name: "Calculators", icon: "🔢" },
  { id: "legal", name: "Legal & Business", icon: "📋" },
  { id: "design", name: "Design Tools", icon: "🎨" },
  { id: "seo", name: "SEO Tools", icon: "🔎" },
] as const;

export const tools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    category: "developer",
    icon: "{ }",
  },
  {
    slug: "base64-encode-decode",
    name: "Base64 Encode / Decode",
    description: "Encode text to Base64 or decode Base64 strings instantly.",
    category: "converter",
    icon: "B64",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4) with one click. Bulk generation supported.",
    category: "generator",
    icon: "ID",
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text in paragraphs, sentences, or words.",
    category: "text",
    icon: "Aa",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs in any text.",
    category: "text",
    icon: "#",
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URLs and query strings. Handles special characters.",
    category: "converter",
    icon: "%",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text.",
    category: "crypto",
    icon: "#!",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with customizable length and characters.",
    category: "generator",
    icon: "***",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between HEX, RGB, and HSL formats.",
    category: "developer",
    icon: "HEX",
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write Markdown and preview the rendered HTML output in real time.",
    category: "developer",
    icon: "MD",
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier / Beautifier",
    description: "Minify or beautify CSS code. Remove whitespace or format for readability.",
    category: "developer",
    icon: "CSS",
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight the differences line by line.",
    category: "text",
    icon: "+/-",
  },
  {
    slug: "epoch-converter",
    name: "Epoch / Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa.",
    category: "converter",
    icon: "UTC",
  },
  {
    slug: "json-csv-converter",
    name: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV format and CSV back to JSON.",
    category: "converter",
    icon: "CSV",
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Convert any text into a URL-friendly slug. Clean, lowercase, hyphenated.",
    category: "text",
    icon: "/-/",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against text with real-time highlighting of matches.",
    category: "developer",
    icon: ".*",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens. View header, payload, and expiration.",
    category: "crypto",
    icon: "JWT",
  },
  {
    slug: "html-encoder-decoder",
    name: "HTML Encoder / Decoder",
    description: "Encode special characters to HTML entities or decode them back to text.",
    category: "converter",
    icon: "&lt;",
  },
  {
    slug: "cron-generator",
    name: "Cron Expression Generator",
    description: "Build and understand cron expressions with a visual, interactive editor.",
    category: "developer",
    icon: "0 *",
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between decimal, binary, octal, and hexadecimal.",
    category: "converter",
    icon: "0x",
  },
  {
    slug: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text between uppercase, lowercase, camelCase, snake_case, and more.",
    category: "text",
    icon: "Aa",
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions in octal and symbolic notation.",
    category: "developer",
    icon: "rwx",
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between ISO 8601, Unix timestamps, and human-readable dates.",
    category: "converter",
    icon: "T",
  },
  {
    slug: "backslash-escape",
    name: "Backslash Escape / Unescape",
    description: "Escape or unescape special characters like newlines, tabs, and quotes.",
    category: "converter",
    icon: "\\n",
  },
  {
    slug: "ip-address-info",
    name: "IP Address Analyzer",
    description: "Analyze IPv4/IPv6 addresses: class, scope, binary, and hex representation.",
    category: "developer",
    icon: "IP",
  },
  {
    slug: "line-sorter",
    name: "Line Sorter & Deduplicator",
    description: "Sort lines alphabetically, numerically, or by length. Remove duplicates.",
    category: "text",
    icon: "A↓",
  },
  {
    slug: "json-path-finder",
    name: "JSON Path Finder",
    description: "Extract all paths from a JSON object. Filter and copy JSONPath expressions.",
    category: "developer",
    icon: "$.x",
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios and resize dimensions proportionally.",
    category: "converter",
    icon: "16:9",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with proper indentation and keywords.",
    category: "developer",
    icon: "SQL",
  },
  {
    slug: "placeholder-image",
    name: "Placeholder Image Generator",
    description: "Generate lightweight SVG placeholder images with custom dimensions and colors.",
    category: "generator",
    icon: "IMG",
  },
  {
    slug: "yaml-json-converter",
    name: "YAML ↔ JSON Converter",
    description: "Convert between YAML and JSON formats instantly.",
    category: "converter",
    icon: "YML",
  },
  {
    slug: "yaml-validator",
    name: "YAML Validator",
    description: "Validate YAML syntax online. Find errors with line numbers and see parsed JSON output.",
    category: "developer",
    icon: "Y✓",
  },
  {
    slug: "unicode-lookup",
    name: "Unicode Character Lookup",
    description: "Inspect characters: code points, HTML entities, CSS escapes, UTF-8 bytes.",
    category: "text",
    icon: "U+",
  },
  {
    slug: "hex-rgb-converter",
    name: "HEX ↔ RGB Converter",
    description: "Convert between HEX, RGB, and HSL color values.",
    category: "converter",
    icon: "RGB",
  },
  {
    slug: "js-minifier",
    name: "JavaScript Minifier",
    description: "Minify JavaScript code by removing comments and whitespace.",
    category: "developer",
    icon: "JS",
  },
  {
    slug: "text-repeater",
    name: "Text Repeater",
    description: "Repeat any text multiple times with custom separators.",
    category: "text",
    icon: "x10",
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown format. Handles headings, lists, links, and more.",
    category: "converter",
    icon: "→MD",
  },
  {
    slug: "byte-counter",
    name: "Byte Counter",
    description: "Count bytes, characters, and code points. Shows UTF-8 and UTF-16 sizes.",
    category: "text",
    icon: "B",
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    description: "Generate random numbers within a custom range with various options.",
    category: "generator",
    icon: "?#",
  },
  {
    slug: "morse-code",
    name: "Morse Code Translator",
    description: "Translate text to Morse code and Morse code back to text.",
    category: "converter",
    icon: "·−",
  },
  {
    slug: "rot13",
    name: "ROT13 / Caesar Cipher",
    description: "Encode/decode text with ROT13, ROT47, or custom Caesar cipher shift.",
    category: "crypto",
    icon: "R13",
  },
  {
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create CSS linear and radial gradients with a visual editor and presets.",
    category: "developer",
    icon: "▓",
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Generate TypeScript interfaces from JSON data automatically.",
    category: "developer",
    icon: "TS",
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary",
    description: "Convert text to binary, hexadecimal, octal, or decimal representation.",
    category: "converter",
    icon: "010",
  },
  {
    slug: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Create Markdown tables with a visual editor and column alignment.",
    category: "text",
    icon: "| |",
  },
  {
    slug: "json-stringify",
    name: "JSON Stringify / Parse",
    description: "Convert between formatted and stringified (escaped) JSON.",
    category: "developer",
    icon: '""',
  },
  {
    slug: "box-shadow-generator",
    name: "CSS Box Shadow Generator",
    description: "Create box shadows with a visual editor. Adjust offset, blur, spread, and color.",
    category: "developer",
    icon: "▪",
  },
  {
    slug: "px-converter",
    name: "PX / REM / EM Converter",
    description: "Convert between px, rem, em, pt, vw, vh, and percent CSS units.",
    category: "converter",
    icon: "px",
  },
  {
    slug: "og-meta-generator",
    name: "Open Graph Generator",
    description: "Generate Open Graph and Twitter Card meta tags for social media previews.",
    category: "developer",
    icon: "OG",
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Parse URLs into protocol, hostname, port, path, query params, and hash.",
    category: "developer",
    icon: "://",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate SVG favicons with emoji, text, or initials. No upload needed.",
    category: "generator",
    icon: "ICO",
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs. Customize colors and download as PNG or SVG.",
    category: "generator",
    icon: "QR",
  },
  {
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    description: "Validate JSON data against a JSON Schema. Check types, required fields, and constraints.",
    category: "developer",
    icon: "{}✓",
  },
  {
    slug: "github-readme-generator",
    name: "GitHub README Generator",
    description: "Create an awesome GitHub profile README with stats, badges, and social links.",
    category: "generator",
    icon: "GH",
  },
  {
    slug: "tailwind-color-generator",
    name: "Tailwind Color Generator",
    description: "Generate Tailwind CSS color palettes (50-950) from any base color.",
    category: "developer",
    icon: "TW",
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Format, beautify, and validate XML data with custom indentation.",
    category: "developer",
    icon: "XML",
  },
  {
    slug: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate subnet details from CIDR notation. Network, broadcast, host range, and netmask.",
    category: "developer",
    icon: "IP/",
  },
  {
    slug: "robots-txt-generator",
    name: "robots.txt Generator",
    description: "Generate robots.txt files with crawl rules, sitemaps, and bot-specific directives.",
    category: "developer",
    icon: "BOT",
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes. Random, analogous, complementary, and triadic schemes.",
    category: "generator",
    icon: "PAL",
  },
  {
    slug: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Complete reference of all HTTP status codes (1xx-5xx) with descriptions and examples.",
    category: "developer",
    icon: "200",
  },
  {
    slug: "regex-cheat-sheet",
    name: "Regex Cheat Sheet",
    description: "Quick reference for regular expressions. Character classes, quantifiers, groups, and common patterns.",
    category: "developer",
    icon: "/./",
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate HTML meta tags for SEO. Title, description, viewport, robots, and canonical tags.",
    category: "developer",
    icon: "TAG",
  },
  {
    slug: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate a free privacy policy for your website. GDPR, cookies, and data collection covered.",
    category: "generator",
    icon: "PP",
  },
  {
    slug: "base64-image-encoder",
    name: "Base64 Image Encoder",
    description: "Convert images to Base64 strings. Supports PNG, JPG, GIF, SVG, and WebP formats.",
    category: "converter",
    icon: "IMG",
  },
  {
    slug: "border-radius-generator",
    name: "CSS Border Radius Generator",
    description: "Create CSS border-radius values with a visual editor. Adjust each corner individually.",
    category: "developer",
    icon: "◜◝",
  },
  {
    slug: "htaccess-generator",
    name: ".htaccess Generator",
    description: "Generate .htaccess rules for redirects, HTTPS, caching, and security headers.",
    category: "developer",
    icon: ".ht",
  },
  {
    slug: "emoji-picker",
    name: "Emoji Picker",
    description: "Search, browse, and copy emojis to clipboard. Organized by category with Unicode info.",
    category: "text",
    icon: "😀",
  },
  {
    slug: "color-contrast-checker",
    name: "Color Contrast Checker",
    description: "Check WCAG 2.1 color contrast ratios. Validate AA and AAA accessibility standards.",
    category: "developer",
    icon: "AA",
  },
  {
    slug: "flexbox-generator",
    name: "CSS Flexbox Generator",
    description: "Generate CSS flexbox layouts with a visual editor. Set direction, alignment, and wrapping.",
    category: "developer",
    icon: "FLX",
  },
  {
    slug: "text-shadow-generator",
    name: "CSS Text Shadow Generator",
    description: "Create CSS text-shadow effects with a visual editor. Multiple shadows and presets.",
    category: "developer",
    icon: "Ts",
  },
  {
    slug: "json-to-xml",
    name: "JSON to XML Converter",
    description: "Convert JSON data to XML format. Handles nested objects, arrays, and attributes.",
    category: "converter",
    icon: "→XM",
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown text to clean HTML code. Supports headings, lists, links, and code blocks.",
    category: "converter",
    icon: "→HT",
  },
  {
    slug: "fake-data-generator",
    name: "Fake Data Generator",
    description: "Generate realistic fake data for testing. Names, emails, phone numbers, and addresses.",
    category: "generator",
    icon: "FAK",
  },
  {
    slug: "csv-viewer",
    name: "CSV Viewer",
    description: "View CSV data as a formatted table. Sort columns, search, and filter rows.",
    category: "converter",
    icon: "TBL",
  },
  {
    slug: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON objects and highlight added, removed, and modified keys.",
    category: "developer",
    icon: "J±",
  },
  {
    slug: "toc-generator",
    name: "Table of Contents Generator",
    description: "Generate a table of contents from Markdown headings. Create linked TOC for README files.",
    category: "text",
    icon: "TOC",
  },
  {
    slug: "git-cheat-sheet",
    name: "Git Cheat Sheet",
    description: "Essential Git commands reference. Setup, branching, merging, stashing, and more.",
    category: "developer",
    icon: "GIT",
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Create JSON Web Tokens with custom payload, expiration, and HS256 signing.",
    category: "crypto",
    icon: "JWG",
  },
  {
    slug: "css-grid-generator",
    name: "CSS Grid Generator",
    description: "Create CSS Grid layouts with a visual editor. Set columns, rows, and gap.",
    category: "developer",
    icon: "GRD",
  },
  {
    slug: "open-source-licenses",
    name: "Open Source Licenses",
    description: "Compare and copy open source licenses. MIT, Apache, GPL, BSD, ISC, and more.",
    category: "developer",
    icon: "LIC",
  },
  {
    slug: "html-minifier",
    name: "HTML Minifier",
    description: "Minify or beautify HTML code. Remove whitespace and comments to reduce file size.",
    category: "converter",
    icon: "H<>",
  },
  {
    slug: "css-animation-generator",
    name: "CSS Animation Generator",
    description: "Create CSS keyframe animations with a visual editor. Preview and copy animation code.",
    category: "developer",
    icon: "ANI",
  },
  {
    slug: "xml-to-json",
    name: "XML to JSON Converter",
    description: "Convert XML data to JSON format. Handles nested elements, attributes, and arrays.",
    category: "converter",
    icon: "X→J",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between units of length, weight, temperature, speed, area, and volume.",
    category: "converter",
    icon: "CM",
  },
  {
    slug: "time-zone-converter",
    name: "Time Zone Converter",
    description: "Convert time between different time zones. Compare multiple zones at a glance.",
    category: "converter",
    icon: "TZ",
  },
  {
    slug: "reading-time-calculator",
    name: "Reading Time Calculator",
    description: "Estimate reading time and speaking time for any text. Word and character stats included.",
    category: "text",
    icon: "RT",
  },
  {
    slug: "color-blindness-simulator",
    name: "Color Blindness Simulator",
    description: "Preview how colors appear with different types of color vision deficiency.",
    category: "developer",
    icon: "EYE",
  },
  {
    slug: "json-to-go",
    name: "JSON to Go Struct",
    description: "Generate Go struct definitions from JSON data. Handles nested objects and arrays.",
    category: "developer",
    icon: "GO",
  },
  {
    slug: "csv-to-sql",
    name: "CSV to SQL Converter",
    description: "Convert CSV data to SQL INSERT statements or CREATE TABLE queries.",
    category: "converter",
    icon: "→SQ",
  },
  {
    slug: "password-strength-checker",
    name: "Password Strength Checker",
    description: "Analyze password strength with detailed scoring. Get tips to improve security.",
    category: "crypto",
    icon: "PWD",
  },
  {
    slug: "email-validator",
    name: "Email Validator",
    description: "Validate email address format and syntax. Check for common mistakes and typos.",
    category: "text",
    icon: "@✓",
  },
  {
    slug: "nginx-config-generator",
    name: "Nginx Config Generator",
    description: "Generate nginx server blocks for static sites, reverse proxy, SSL, and redirects.",
    category: "developer",
    icon: "NGX",
  },
  {
    slug: "screen-resolution-info",
    name: "Screen Resolution Info",
    description: "View your screen resolution, viewport size, DPR, color depth, and device info.",
    category: "developer",
    icon: "RES",
  },
  {
    slug: "keyboard-event-tester",
    name: "Keyboard Event Tester",
    description: "Test keyboard events in real time. See key codes, key names, and event properties.",
    category: "developer",
    icon: "KEY",
  },
  {
    slug: "text-to-nato",
    name: "NATO Phonetic Alphabet",
    description: "Convert text to NATO phonetic alphabet. Alpha, Bravo, Charlie and back.",
    category: "converter",
    icon: "NATO",
  },
  {
    slug: "html-table-generator",
    name: "HTML Table Generator",
    description: "Create HTML tables with a visual editor. Set rows, columns, headers, and styling.",
    category: "generator",
    icon: "TBL",
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    description: "Generate HMAC signatures using SHA-256, SHA-512, and other hash algorithms.",
    category: "crypto",
    icon: "MAC",
  },
  {
    slug: "text-to-ascii-art",
    name: "Text to ASCII Art",
    description: "Convert text to ASCII art with multiple font styles. Copy and share text banners.",
    category: "text",
    icon: "A#",
  },
  {
    slug: "data-size-converter",
    name: "Data Size Converter",
    description: "Convert between bytes, KB, MB, GB, TB, and PB. Binary and decimal units.",
    category: "converter",
    icon: "GB",
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse text characters, words, or lines. Create mirror text and palindromes.",
    category: "text",
    icon: "↔T",
  },
  {
    slug: "toml-to-json",
    name: "TOML ↔ JSON Converter",
    description: "Convert between TOML and JSON formats. Validate TOML syntax and see parsed output.",
    category: "converter",
    icon: "TML",
  },
  {
    slug: "env-editor",
    name: ".env Editor & Validator",
    description: "Edit and validate .env files. Check for duplicates, empty values, and syntax errors.",
    category: "developer",
    icon: "ENV",
  },
  {
    slug: "api-response-mocker",
    name: "API Response Mocker",
    description: "Create mock API responses with custom status codes, headers, and JSON body.",
    category: "developer",
    icon: "API",
  },
  {
    slug: "tailwind-class-sorter",
    name: "Tailwind Class Sorter",
    description: "Sort Tailwind CSS classes in the recommended order. Paste your class string and get sorted output.",
    category: "developer",
    icon: "TWS",
  },
  {
    slug: "regex-to-english",
    name: "Regex to English",
    description: "Translate regular expressions to plain English explanations. Understand any regex pattern.",
    category: "developer",
    icon: "R→E",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images in your browser. Reduce file size without losing quality.",
    category: "media",
    icon: "📦",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to exact pixel dimensions or scale by percentage. Free online image resizer.",
    category: "media",
    icon: "📐",
  },
  {
    slug: "screenshot-to-text",
    name: "Screenshot to Text (OCR)",
    description: "Extract text from images and screenshots using OCR. Supports 100+ languages. Runs in your browser.",
    category: "media",
    icon: "👁️",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract text from PDF files directly in your browser. No upload required. Free PDF text extraction.",
    category: "converter",
    icon: "📄",
  },
  {
    slug: "image-format-converter",
    name: "Image Format Converter",
    description: "Convert images between PNG, JPG, WebP, and BMP formats instantly in your browser.",
    category: "media",
    icon: "🔄",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert one or more images to a PDF document. Arrange pages, set margins, choose page size.",
    category: "converter",
    icon: "📑",
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to natural speech using your browser. Choose voice, speed, and pitch.",
    category: "text",
    icon: "🔊",
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    description: "Convert speech to text in real-time using your microphone. Supports 18+ languages.",
    category: "text",
    icon: "🎤",
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional PDF invoices with line items, tax, and multi-currency support.",
    category: "legal",
    icon: "🧾",
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in CODE128, EAN-13, UPC, CODE39 and more. Download as SVG or PNG.",
    category: "generator",
    icon: "📊",
  },
  {
    slug: "fancy-text-generator",
    name: "Fancy Text Generator",
    description: "Generate fancy Unicode text styles for social media — bold, italic, script, and more.",
    category: "text",
    icon: "✨",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months, days. Find zodiac sign and next birthday.",
    category: "calculator",
    icon: "🎂",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages instantly — find %, percentage change, increases, and decreases.",
    category: "calculator",
    icon: "📐",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop images with drag-and-resize handles. Export as PNG, JPG, or WebP.",
    category: "media",
    icon: "✂️",
  },
  {
    slug: "image-watermark",
    name: "Image Watermark",
    description: "Add text watermarks to images. Center, tile, or corner placement with custom style.",
    category: "media",
    icon: "💧",
  },
  {
    slug: "terms-of-service-generator",
    name: "Terms of Service Generator",
    description: "Generate a free Terms of Service for your website or app. Customizable and instant.",
    category: "legal",
    icon: "📜",
  },
  {
    slug: "pdf-merge",
    name: "PDF Merge",
    description: "Combine multiple PDF files into one document. Reorder and merge instantly in your browser.",
    category: "converter",
    icon: "📎",
  },
  {
    slug: "pdf-split",
    name: "PDF Split",
    description: "Extract specific pages from a PDF. Select page ranges or individual pages. Free and private.",
    category: "converter",
    icon: "✂️",
  },
  {
    slug: "signature-generator",
    name: "Signature Generator",
    description: "Draw your digital signature and download as PNG or SVG. Free, instant, private.",
    category: "generator",
    icon: "✍️",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index. Supports metric and imperial units with health categories.",
    category: "calculator",
    icon: "⚖️",
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payments, total interest, and cost for any loan. Instant and free.",
    category: "calculator",
    icon: "🏦",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tips and split bills easily. Preset percentages and bill splitting for any group size.",
    category: "calculator",
    icon: "💰",
  },
  {
    slug: "css-glassmorphism-generator",
    name: "CSS Glassmorphism Generator",
    description: "Generate CSS glassmorphism (frosted glass) effects with live preview. Copy ready-to-use CSS.",
    category: "developer",
    icon: "🪟",
  },
  {
    slug: "css-neumorphism-generator",
    name: "CSS Neumorphism Generator",
    description: "Generate soft UI / neumorphism CSS with live preview. Flat, concave, convex, pressed shapes.",
    category: "developer",
    icon: "🔘",
  },
  {
    slug: "dockerfile-generator",
    name: "Dockerfile Generator",
    description: "Generate Dockerfiles with a visual builder. Presets for Node.js, Python, Go, Java.",
    category: "developer",
    icon: "🐳",
  },
  {
    slug: "email-template-builder",
    name: "Email Template Builder",
    description: "Build responsive HTML email templates visually. Customize header, body, CTA. Copy or download.",
    category: "generator",
    icon: "📧",
  },
  {
    slug: "invisible-character-detector",
    name: "Invisible Character Detector",
    description: "Find and remove hidden zero-width and invisible characters from text. Detects 30+ types.",
    category: "text",
    icon: "🔍",
  },
  {
    slug: "text-to-handwriting",
    name: "Text to Handwriting",
    description: "Convert typed text to handwriting-style images. Multiple fonts, custom colors, notebook lines.",
    category: "text",
    icon: "🖊️",
  },
  {
    slug: "resume-builder",
    name: "Resume Builder",
    description: "Build a professional resume and download as PDF. 3 templates, custom colors. Free and private.",
    category: "generator",
    icon: "📄",
  },
  {
    slug: "ai-prompt-generator",
    name: "AI Prompt Generator",
    description: "Generate effective AI prompts for ChatGPT, Claude, Gemini. 17 templates across 5 categories.",
    category: "text",
    icon: "🤖",
  },
  {
    slug: "github-actions-generator",
    name: "GitHub Actions Generator",
    description: "Generate GitHub Actions CI/CD workflows visually. Deploy to Vercel, Netlify, S3, or Docker.",
    category: "developer",
    icon: "⚙️",
  },
  {
    slug: "docker-compose-generator",
    name: "Docker Compose Generator",
    description: "Generate docker-compose.yml files with a visual editor. Presets for PostgreSQL, MySQL, Redis, MongoDB.",
    category: "developer",
    icon: "🐙",
  },
  {
    slug: "font-pairing-suggester",
    name: "Font Pairing Suggester",
    description: "Find beautiful Google Font pairings. 15 curated heading + body combinations with live preview.",
    category: "design",
    icon: "🔤",
  },
  {
    slug: "cron-expression-generator",
    name: "Cron Expression Generator",
    description: "Build and understand cron expressions visually. See next run times and human-readable descriptions.",
    category: "developer",
    icon: "⏰",
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV files. Custom delimiters, file upload, instant download.",
    category: "converter",
    icon: "📊",
  },
  {
    slug: "open-graph-preview",
    name: "Open Graph Preview",
    description: "Preview how your website looks when shared on Facebook, Twitter, LinkedIn, and Discord.",
    category: "seo",
    icon: "👁️",
  },
  {
    slug: "color-gradient-maker",
    name: "Color Gradient Maker",
    description: "Create beautiful CSS gradients. Linear, radial, conic with multi-stop editor and presets.",
    category: "design",
    icon: "🌈",
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON Converter",
    description: "Convert CSV files to JSON. Custom delimiters, quoted fields, auto-detect numbers.",
    category: "converter",
    icon: "🔄",
  },
  {
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate XML sitemaps for your website. Set priorities, change frequencies, and last modified dates.",
    category: "seo",
    icon: "🗺️",
  },
  {
    slug: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly using AI in your browser. 100% private, no server uploads.",
    category: "media",
    icon: "✂️",
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    description: "Convert video clips to animated GIF/WebM. Adjust FPS, size, quality. 100% browser-based.",
    category: "media",
    icon: "🎬",
  },
  {
    slug: "gif-maker",
    name: "GIF Maker",
    description: "Create animated GIFs from images. Upload frames, set speed, reorder. No server uploads.",
    category: "media",
    icon: "🎞️",
  },
  {
    slug: "svg-editor",
    name: "SVG Editor",
    description: "Create and edit SVG graphics visually. Add shapes, colors, text. Export clean SVG code.",
    category: "design",
    icon: "✏️",
  },
  {
    slug: "api-docs-generator",
    name: "API Docs Generator",
    description: "Generate OpenAPI 3.0 (Swagger) documentation. Visual endpoint builder with parameters and tags.",
    category: "developer",
    icon: "📘",
  },
  {
    slug: "color-palette-from-image",
    name: "Color Palette from Image",
    description: "Extract dominant colors from any image. Get hex and RGB values for your design palette.",
    category: "design",
    icon: "🎨",
  },
  {
    slug: "json-schema-generator",
    name: "JSON Schema Generator",
    description: "Generate JSON Schema from any JSON data. Auto-detect formats like email, URI, date, UUID.",
    category: "developer",
    icon: "📐",
  },
  {
    slug: "webp-to-png",
    name: "WebP to PNG Converter",
    description: "Convert WebP images to PNG instantly in your browser. No upload, no tracking.",
    category: "converter",
    icon: "W>P",
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG Converter",
    description: "Convert WebP to JPG (JPEG) with optional quality settings. Runs fully client-side.",
    category: "converter",
    icon: "W>J",
  },
  {
    slug: "exif-viewer",
    name: "EXIF Metadata Viewer",
    description: "Read camera and EXIF metadata from JPEG photos directly in your browser.",
    category: "media",
    icon: "EXIF",
  },
  {
    slug: "exif-metadata-remover",
    name: "Image Metadata Remover",
    description: "Strip EXIF and hidden metadata from photos before sharing. 100% local processing.",
    category: "media",
    icon: "META",
  },
  {
    slug: "token-counter",
    name: "AI Token Counter",
    description: "Estimate token usage for prompts and texts across AI models. Fast browser-side estimate.",
    category: "developer",
    icon: "TOK",
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG Converter",
    description: "Convert HEIC/HEIF photos to JPG directly in your browser with no server upload.",
    category: "converter",
    icon: "H>J",
  },
  {
    slug: "heic-to-png",
    name: "HEIC to PNG Converter",
    description: "Convert HEIC/HEIF images to PNG in-browser. Private and batch-friendly.",
    category: "converter",
    icon: "H>P",
  },
  {
    slug: "avif-to-jpg",
    name: "AVIF to JPG Converter",
    description: "Convert AVIF images to JPG (JPEG) with quality control. Browser-only processing.",
    category: "converter",
    icon: "A>J",
  },
  {
    slug: "mp4-to-mp3",
    name: "MP4 to MP3 Converter",
    description: "Extract audio from MP4 videos and export MP3 directly in your browser.",
    category: "converter",
    icon: "M>3",
  },
  {
    slug: "video-compressor",
    name: "Video Compressor",
    description: "Compress videos in your browser by lowering resolution and bitrate. No uploads.",
    category: "media",
    icon: "VCC",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG Converter",
    description: "Convert PDF pages to JPG images with quality and scale controls in your browser.",
    category: "converter",
    icon: "P>J",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF Converter",
    description: "Merge JPG/JPEG images into one PDF directly in your browser.",
    category: "converter",
    icon: "J>P",
  },
  {
    slug: "png-to-pdf",
    name: "PNG to PDF Converter",
    description: "Convert PNG images to PDF with optional transparency flattening.",
    category: "converter",
    icon: "N>P",
  },
  {
    slug: "base64-to-pdf",
    name: "Base64 to PDF Converter",
    description: "Decode Base64 strings or data URLs and download as PDF locally.",
    category: "converter",
    icon: "B>P",
  },
  {
    slug: "openai-batch-jsonl-validator",
    name: "OpenAI Batch JSONL Validator",
    description: "Validate Batch API JSONL lines, detect errors, and export valid records.",
    category: "developer",
    icon: "BJL",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG Converter",
    description: "Convert PDF pages to PNG images in-browser with adjustable render scale.",
    category: "converter",
    icon: "P>N",
  },
  {
    slug: "pdf-to-image",
    name: "PDF to Image Converter",
    description: "Convert PDF pages to PNG, JPG, or WebP with page-range and quality controls.",
    category: "converter",
    icon: "P>I",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word Converter",
    description: "Extract text from PDFs and export a Word-compatible DOC file in-browser.",
    category: "converter",
    icon: "P>W",
  },
  {
    slug: "c2pa-viewer",
    name: "C2PA Viewer",
    description: "Inspect files for Content Credentials/C2PA markers locally in your browser.",
    category: "media",
    icon: "C2P",
  },
  {
    slug: "pii-redactor",
    name: "PII Redactor",
    description: "Detect and redact emails, phones, cards, IBAN, IPs, and tokens from text.",
    category: "crypto",
    icon: "PII",
  },
];




