"use client";

import { useState, useMemo } from "react";
import ToolLayout from "@/components/ToolLayout";
import CopyButton from "@/components/CopyButton";

type ServerType = "static" | "proxy" | "php" | "spa";

export default function NginxConfigGenerator() {
  // Server type
  const [serverType, setServerType] = useState<ServerType>("static");

  // Common fields
  const [serverName, setServerName] = useState("example.com");
  const [listenPort, setListenPort] = useState(80);
  const [rootDir, setRootDir] = useState("/var/www/html");

  // SSL
  const [sslEnabled, setSslEnabled] = useState(false);
  const [sslCertPath, setSslCertPath] = useState("/etc/nginx/ssl/cert.pem");
  const [sslKeyPath, setSslKeyPath] = useState("/etc/nginx/ssl/key.pem");
  const [redirectHttpToHttps, setRedirectHttpToHttps] = useState(false);

  // Reverse Proxy
  const [proxyPassUrl, setProxyPassUrl] = useState("http://localhost:3000");
  const [websocketSupport, setWebsocketSupport] = useState(false);

  // PHP
  const [phpFpmSocket, setPhpFpmSocket] = useState("unix:/run/php/php8.2-fpm.sock");

  // Additional options
  const [gzipEnabled, setGzipEnabled] = useState(false);
  const [securityHeaders, setSecurityHeaders] = useState(false);
  const [customErrorPages, setCustomErrorPages] = useState(false);
  const [error404Page, setError404Page] = useState("/404.html");
  const [error500Page, setError500Page] = useState("/50x.html");
  const [accessLog, setAccessLog] = useState("/var/log/nginx/access.log");
  const [errorLog, setErrorLog] = useState("/var/log/nginx/error.log");
  const [clientMaxBodySize, setClientMaxBodySize] = useState("10m");

  const nginxConfig = useMemo(() => {
    const lines: string[] = [];
    const domain = serverName.trim() || "example.com";
    const root = rootDir.trim() || "/var/www/html";
    const port = sslEnabled ? 443 : listenPort;

    lines.push("# Generated by CodeUtilo.com Nginx Config Generator");
    lines.push("");

    // HTTP → HTTPS redirect block
    if (sslEnabled && redirectHttpToHttps) {
      lines.push("server {");
      lines.push(`    listen 80;`);
      lines.push(`    listen [::]:80;`);
      lines.push(`    server_name ${domain} www.${domain};`);
      lines.push("");
      lines.push("    # Redirect all HTTP to HTTPS");
      lines.push(`    return 301 https://$host$request_uri;`);
      lines.push("}");
      lines.push("");
    }

    // Main server block
    lines.push("server {");
    if (sslEnabled) {
      lines.push(`    listen 443 ssl http2;`);
      lines.push(`    listen [::]:443 ssl http2;`);
    } else {
      lines.push(`    listen ${port};`);
      lines.push(`    listen [::]:${port};`);
    }
    lines.push(`    server_name ${domain} www.${domain};`);
    lines.push("");

    // Root and index (not needed for pure proxy, but useful reference)
    if (serverType !== "proxy") {
      lines.push(`    root ${root};`);
      if (serverType === "php") {
        lines.push(`    index index.php index.html index.htm;`);
      } else {
        lines.push(`    index index.html index.htm;`);
      }
      lines.push("");
    }

    // SSL certificates
    if (sslEnabled) {
      const cert = sslCertPath.trim() || "/etc/nginx/ssl/cert.pem";
      const key = sslKeyPath.trim() || "/etc/nginx/ssl/key.pem";
      lines.push("    # SSL Configuration");
      lines.push(`    ssl_certificate ${cert};`);
      lines.push(`    ssl_certificate_key ${key};`);
      lines.push("    ssl_protocols TLSv1.2 TLSv1.3;");
      lines.push("    ssl_ciphers HIGH:!aNULL:!MD5;");
      lines.push("    ssl_prefer_server_ciphers on;");
      lines.push("");
    }

    // Logs
    const alog = accessLog.trim() || "/var/log/nginx/access.log";
    const elog = errorLog.trim() || "/var/log/nginx/error.log";
    lines.push(`    access_log ${alog};`);
    lines.push(`    error_log ${elog};`);
    lines.push("");

    // Client max body size
    const bodySize = clientMaxBodySize.trim() || "10m";
    lines.push(`    client_max_body_size ${bodySize};`);
    lines.push("");

    // Gzip
    if (gzipEnabled) {
      lines.push("    # Gzip Compression");
      lines.push("    gzip on;");
      lines.push("    gzip_vary on;");
      lines.push("    gzip_min_length 1024;");
      lines.push("    gzip_proxied any;");
      lines.push("    gzip_comp_level 6;");
      lines.push(
        "    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml image/svg+xml;"
      );
      lines.push("");
    }

    // Security headers
    if (securityHeaders) {
      lines.push("    # Security Headers");
      lines.push('    add_header X-Frame-Options "SAMEORIGIN" always;');
      lines.push('    add_header X-Content-Type-Options "nosniff" always;');
      lines.push('    add_header X-XSS-Protection "1; mode=block" always;');
      lines.push(
        '    add_header Referrer-Policy "strict-origin-when-cross-origin" always;'
      );
      lines.push(
        "    add_header Content-Security-Policy \"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;\" always;"
      );
      lines.push("");
    }

    // Custom error pages
    if (customErrorPages) {
      lines.push("    # Custom Error Pages");
      if (error404Page.trim())
        lines.push(`    error_page 404 ${error404Page.trim()};`);
      if (error500Page.trim())
        lines.push(
          `    error_page 500 502 503 504 ${error500Page.trim()};`
        );
      lines.push("");
    }

    // Location block(s) based on server type
    if (serverType === "static") {
      lines.push("    location / {");
      lines.push("        try_files $uri $uri/ =404;");
      lines.push("    }");
    } else if (serverType === "spa") {
      lines.push("    location / {");
      lines.push("        try_files $uri $uri/ /index.html;");
      lines.push("    }");
      lines.push("");
      lines.push("    # Cache static assets");
      lines.push(
        "    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {"
      );
      lines.push("        expires 1y;");
      lines.push('        add_header Cache-Control "public, immutable";');
      lines.push("    }");
    } else if (serverType === "proxy") {
      const upstream = proxyPassUrl.trim() || "http://localhost:3000";
      lines.push("    location / {");
      lines.push(`        proxy_pass ${upstream};`);
      lines.push("        proxy_http_version 1.1;");
      lines.push(
        "        proxy_set_header Host $host;"
      );
      lines.push(
        "        proxy_set_header X-Real-IP $remote_addr;"
      );
      lines.push(
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;"
      );
      lines.push(
        "        proxy_set_header X-Forwarded-Proto $scheme;"
      );
      if (websocketSupport) {
        lines.push(
          "        proxy_set_header Upgrade $http_upgrade;"
        );
        lines.push(
          '        proxy_set_header Connection "upgrade";'
        );
      } else {
        lines.push(
          '        proxy_set_header Connection "";'
        );
      }
      lines.push("        proxy_cache_bypass $http_upgrade;");
      lines.push("    }");
    } else if (serverType === "php") {
      const socket = phpFpmSocket.trim() || "unix:/run/php/php8.2-fpm.sock";
      lines.push("    location / {");
      lines.push("        try_files $uri $uri/ =404;");
      lines.push("    }");
      lines.push("");
      lines.push("    location ~ \\.php$ {");
      lines.push("        include snippets/fastcgi-php.conf;");
      lines.push(`        fastcgi_pass ${socket};`);
      lines.push("        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;");
      lines.push("        include fastcgi_params;");
      lines.push("    }");
      lines.push("");
      lines.push("    location ~ /\\.ht {");
      lines.push("        deny all;");
      lines.push("    }");
    }

    lines.push("}");

    return lines.join("\n");
  }, [
    serverType,
    serverName,
    listenPort,
    rootDir,
    sslEnabled,
    sslCertPath,
    sslKeyPath,
    redirectHttpToHttps,
    proxyPassUrl,
    websocketSupport,
    phpFpmSocket,
    gzipEnabled,
    securityHeaders,
    customErrorPages,
    error404Page,
    error500Page,
    accessLog,
    errorLog,
    clientMaxBodySize,
  ]);

  const inputClass =
    "w-full rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none";
  const labelClass = "mb-1 block text-xs font-medium text-gray-600 dark:text-gray-400";
  const sectionClass = "border-t border-gray-100 dark:border-gray-800 pt-5";

  return (
    <ToolLayout
      title="Nginx Config Generator"
      description="Generate Nginx server block configurations for static sites, reverse proxies, PHP apps, and SPAs. Includes SSL, gzip, security headers, and more."
      relatedTools={[
        "htaccess-generator",
        "robots-txt-generator",
        "meta-tag-generator",
      ]}
    >
      <div className="space-y-6">
        {/* Server Type */}
        <div>
          <span className="block text-sm font-semibold text-gray-900 dark:text-gray-100 mb-3">
            Server Type
          </span>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            {[
              { value: "static" as const, label: "Static Website" },
              { value: "proxy" as const, label: "Reverse Proxy" },
              { value: "php" as const, label: "PHP (FastCGI)" },
              { value: "spa" as const, label: "SPA" },
            ].map((opt) => (
              <label
                key={opt.value}
                className={`flex cursor-pointer items-center justify-center gap-2 rounded-lg border px-3 py-2.5 text-sm font-medium transition-colors ${
                  serverType === opt.value
                    ? "border-blue-500 dark:border-blue-400 bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-300"
                    : "border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:border-gray-600 dark:hover:border-gray-600 hover:bg-gray-50 dark:bg-gray-950 dark:hover:bg-gray-800"
                }`}
              >
                <input
                  type="radio"
                  name="serverType"
                  value={opt.value}
                  checked={serverType === opt.value}
                  onChange={() => setServerType(opt.value)}
                  className="sr-only"
                />
                {opt.label}
              </label>
            ))}
          </div>
        </div>

        {/* Common Fields */}
        <div className={sectionClass}>
          <span className="block text-sm font-semibold text-gray-900 dark:text-gray-100 mb-3">
            General Settings
          </span>
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className={labelClass}>Server Name / Domain</label>
              <input
                type="text"
                value={serverName}
                onChange={(e) => setServerName(e.target.value)}
                placeholder="example.com"
                className={inputClass}
              />
            </div>
            <div>
              <label className={labelClass}>Listen Port</label>
              <input
                type="number"
                value={listenPort}
                onChange={(e) => setListenPort(Number(e.target.value))}
                min={1}
                max={65535}
                placeholder="80"
                className={inputClass}
                disabled={sslEnabled}
              />
              {sslEnabled && (
                <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">
                  Port overridden to 443 when SSL is enabled.
                </p>
              )}
            </div>
            {serverType !== "proxy" && (
              <div className="sm:col-span-2">
                <label className={labelClass}>Root Directory</label>
                <input
                  type="text"
                  value={rootDir}
                  onChange={(e) => setRootDir(e.target.value)}
                  placeholder="/var/www/html"
                  className={inputClass}
                />
              </div>
            )}
          </div>
        </div>

        {/* SSL / HTTPS */}
        <div className={sectionClass}>
          <label className="flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-gray-100 cursor-pointer">
            <input
              type="checkbox"
              checked={sslEnabled}
              onChange={(e) => setSslEnabled(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Enable SSL / HTTPS
          </label>
          {sslEnabled && (
            <div className="ml-6 mt-4 space-y-4">
              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <label className={labelClass}>SSL Certificate Path</label>
                  <input
                    type="text"
                    value={sslCertPath}
                    onChange={(e) => setSslCertPath(e.target.value)}
                    placeholder="/etc/nginx/ssl/cert.pem"
                    className={inputClass}
                  />
                </div>
                <div>
                  <label className={labelClass}>SSL Key Path</label>
                  <input
                    type="text"
                    value={sslKeyPath}
                    onChange={(e) => setSslKeyPath(e.target.value)}
                    placeholder="/etc/nginx/ssl/key.pem"
                    className={inputClass}
                  />
                </div>
              </div>
              <label className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400 cursor-pointer">
                <input
                  type="checkbox"
                  checked={redirectHttpToHttps}
                  onChange={(e) => setRedirectHttpToHttps(e.target.checked)}
                  className="rounded border-gray-300 dark:border-gray-600"
                />
                Redirect HTTP to HTTPS (adds separate server block on port 80)
              </label>
            </div>
          )}
        </div>

        {/* Reverse Proxy Options */}
        {serverType === "proxy" && (
          <div className={sectionClass}>
            <span className="block text-sm font-semibold text-gray-900 dark:text-gray-100 mb-3">
              Reverse Proxy Settings
            </span>
            <div className="space-y-4">
              <div>
                <label className={labelClass}>Proxy Pass URL</label>
                <input
                  type="text"
                  value={proxyPassUrl}
                  onChange={(e) => setProxyPassUrl(e.target.value)}
                  placeholder="http://localhost:3000"
                  className={inputClass}
                />
              </div>
              <label className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400 cursor-pointer">
                <input
                  type="checkbox"
                  checked={websocketSupport}
                  onChange={(e) => setWebsocketSupport(e.target.checked)}
                  className="rounded border-gray-300 dark:border-gray-600"
                />
                Enable WebSocket Support
              </label>
            </div>
          </div>
        )}

        {/* PHP Options */}
        {serverType === "php" && (
          <div className={sectionClass}>
            <span className="block text-sm font-semibold text-gray-900 dark:text-gray-100 mb-3">
              PHP-FPM Settings
            </span>
            <div>
              <label className={labelClass}>PHP-FPM Socket Path</label>
              <input
                type="text"
                value={phpFpmSocket}
                onChange={(e) => setPhpFpmSocket(e.target.value)}
                placeholder="unix:/run/php/php8.2-fpm.sock"
                className={inputClass}
              />
              <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">
                Use a TCP address like <code>127.0.0.1:9000</code> if not using a Unix socket.
              </p>
            </div>
          </div>
        )}

        {/* Additional Options */}
        <div className={sectionClass}>
          <span className="block text-sm font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Additional Options
          </span>
          <div className="space-y-4">
            {/* Gzip */}
            <div>
              <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100 cursor-pointer">
                <input
                  type="checkbox"
                  checked={gzipEnabled}
                  onChange={(e) => setGzipEnabled(e.target.checked)}
                  className="rounded border-gray-300 dark:border-gray-600"
                />
                Enable Gzip Compression
              </label>
              <p className="ml-6 mt-0.5 text-xs text-gray-500 dark:text-gray-400">
                Compress HTML, CSS, JS, JSON, XML, and SVG responses.
              </p>
            </div>

            {/* Security Headers */}
            <div>
              <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100 cursor-pointer">
                <input
                  type="checkbox"
                  checked={securityHeaders}
                  onChange={(e) => setSecurityHeaders(e.target.checked)}
                  className="rounded border-gray-300 dark:border-gray-600"
                />
                Add Security Headers
              </label>
              {securityHeaders && (
                <ul className="ml-6 mt-2 text-xs text-gray-500 dark:text-gray-400 space-y-0.5 list-disc list-inside">
                  <li>X-Frame-Options: SAMEORIGIN</li>
                  <li>X-Content-Type-Options: nosniff</li>
                  <li>X-XSS-Protection: 1; mode=block</li>
                  <li>Referrer-Policy: strict-origin-when-cross-origin</li>
                  <li>Content-Security-Policy (default)</li>
                </ul>
              )}
            </div>

            {/* Custom Error Pages */}
            <div>
              <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100 cursor-pointer">
                <input
                  type="checkbox"
                  checked={customErrorPages}
                  onChange={(e) => setCustomErrorPages(e.target.checked)}
                  className="rounded border-gray-300 dark:border-gray-600"
                />
                Custom Error Pages
              </label>
              {customErrorPages && (
                <div className="ml-6 mt-3 grid gap-3 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>404 Page Path</label>
                    <input
                      type="text"
                      value={error404Page}
                      onChange={(e) => setError404Page(e.target.value)}
                      placeholder="/404.html"
                      className={inputClass}
                    />
                  </div>
                  <div>
                    <label className={labelClass}>500/502/503/504 Page Path</label>
                    <input
                      type="text"
                      value={error500Page}
                      onChange={(e) => setError500Page(e.target.value)}
                      placeholder="/50x.html"
                      className={inputClass}
                    />
                  </div>
                </div>
              )}
            </div>

            {/* Log Paths */}
            <div className="grid gap-3 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Access Log Path</label>
                <input
                  type="text"
                  value={accessLog}
                  onChange={(e) => setAccessLog(e.target.value)}
                  placeholder="/var/log/nginx/access.log"
                  className={inputClass}
                />
              </div>
              <div>
                <label className={labelClass}>Error Log Path</label>
                <input
                  type="text"
                  value={errorLog}
                  onChange={(e) => setErrorLog(e.target.value)}
                  placeholder="/var/log/nginx/error.log"
                  className={inputClass}
                />
              </div>
            </div>

            {/* Client Max Body Size */}
            <div>
              <label className={labelClass}>Client Max Body Size</label>
              <input
                type="text"
                value={clientMaxBodySize}
                onChange={(e) => setClientMaxBodySize(e.target.value)}
                placeholder="10m"
                className="rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none w-32"
              />
              <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">
                e.g. <code>10m</code>, <code>50m</code>, <code>1g</code>. Controls the maximum allowed size of request bodies.
              </p>
            </div>
          </div>
        </div>

        {/* Generated Output */}
        <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
          <div className="mb-2 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-gray-100">
              Generated Nginx Config
            </h3>
            <CopyButton text={nginxConfig} />
          </div>
          <pre className="overflow-x-auto rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-950 p-4 text-sm leading-relaxed">
            <code>{nginxConfig}</code>
          </pre>
          <p className="mt-2 text-xs text-gray-400 dark:text-gray-500">
            Save this as <code>/etc/nginx/sites-available/your-site.conf</code> and enable it with <code>sudo nginx -t &amp;&amp; sudo systemctl reload nginx</code>.
          </p>
        </div>
      </div>

      
      {/* SEO Content */}
      <div className="mt-12 space-y-6 text-gray-600 dark:text-gray-400 text-sm leading-relaxed border-t border-gray-200 dark:border-gray-700 pt-8">
        <h2 className="text-xl font-bold text-gray-800 dark:text-gray-200">
          About This Tool
        </h2>
        <p>
          The Nginx Config Generator is a free online tool available on CodeUtilo. Generate nginx server blocks for static sites, reverse proxy, SSL, and redirects. All processing happens directly in your browser — no data is ever sent to any server, ensuring your privacy and security. No signup or installation is required.
        </p>

        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          Key Features
        </h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Browser-Based Processing</strong> — All nginx config generator operations run locally in your browser using JavaScript. Your data never leaves your device.
          </li>
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Instant Results</strong> — Get results immediately as you type or paste your input. No waiting for server responses or page reloads.
          </li>
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Free &amp; No Signup</strong> — Use the nginx config generator as many times as you need without creating an account or paying anything.
          </li>
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Mobile Friendly</strong> — Works on desktop, tablet, and mobile browsers. Access this tool from any device with an internet connection.
          </li>
        </ul>

        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          Common Use Cases
        </h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Using the nginx config generator for day-to-day development tasks</li>
          <li>Saving time on repetitive tasks by using a browser-based tool instead of writing custom code</li>
          <li>Working on projects where installing software is not an option (school, work, shared computers)</li>
          <li>Quick prototyping and debugging without switching to a terminal or IDE</li>
          <li>Sharing the tool link with colleagues who need the same functionality</li>
        </ul>

        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          How to Use
        </h2>
        <p>
          Enter your input in the text area provided and the nginx config generator will process it instantly. Use the Copy button to copy the result to your clipboard. All operations are performed locally in your browser — no data is transmitted to any server.
        </p>
      </div>
    </ToolLayout>
  );
}
