"use client";

import { useState, useMemo } from "react";
import ToolLayout from "@/components/ToolLayout";
import CopyButton from "@/components/CopyButton";

interface Redirect {
  id: number;
  source: string;
  destination: string;
  type: "301" | "302";
}

interface ErrorPages {
  e400: string;
  e403: string;
  e404: string;
  e500: string;
}

const CACHE_EXPIRY_OPTIONS = [
  { label: "1 week", value: "604800" },
  { label: "2 weeks", value: "1209600" },
  { label: "1 month", value: "2592000" },
  { label: "3 months", value: "7776000" },
  { label: "6 months", value: "15552000" },
  { label: "1 year", value: "31536000" },
];

export default function HtaccessGenerator() {
  const [forceHttps, setForceHttps] = useState(false);
  const [wwwOption, setWwwOption] = useState<"none" | "force" | "remove">("none");
  const [customErrorPages, setCustomErrorPages] = useState(false);
  const [errorPages, setErrorPages] = useState<ErrorPages>({
    e400: "/error-400.html",
    e403: "/error-403.html",
    e404: "/error-404.html",
    e500: "/error-500.html",
  });
  const [gzipCompression, setGzipCompression] = useState(false);
  const [browserCaching, setBrowserCaching] = useState(false);
  const [cacheExpiry, setCacheExpiry] = useState("2592000");
  const [securityHeaders, setSecurityHeaders] = useState(false);
  const [xFrameOptions, setXFrameOptions] = useState(true);
  const [xContentTypeOptions, setXContentTypeOptions] = useState(true);
  const [xXssProtection, setXXssProtection] = useState(true);
  const [referrerPolicy, setReferrerPolicy] = useState(true);
  const [contentSecurityPolicy, setContentSecurityPolicy] = useState(true);
  const [blockHotlinking, setBlockHotlinking] = useState(false);
  const [disableDirectoryListing, setDisableDirectoryListing] = useState(false);
  const [redirects, setRedirects] = useState<Redirect[]>([]);
  const [nextId, setNextId] = useState(1);

  const addRedirect = () => {
    setRedirects((prev) => [
      ...prev,
      { id: nextId, source: "", destination: "", type: "301" },
    ]);
    setNextId((prev) => prev + 1);
  };

  const removeRedirect = (id: number) => {
    setRedirects((prev) => prev.filter((r) => r.id !== id));
  };

  const updateRedirect = (id: number, field: keyof Redirect, value: string) => {
    setRedirects((prev) =>
      prev.map((r) => (r.id === id ? { ...r, [field]: value } : r))
    );
  };

  const htaccessContent = useMemo(() => {
    const lines: string[] = [];
    lines.push("# Generated by CodeUtilo.com .htaccess Generator");
    lines.push("");

    // Force HTTPS
    if (forceHttps) {
      lines.push("# Force HTTPS");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTPS} off");
      lines.push("RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    // WWW handling
    if (wwwOption === "force") {
      lines.push("# Force WWW");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]");
      lines.push("RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    } else if (wwwOption === "remove") {
      lines.push("# Remove WWW");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
      lines.push("RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    // Custom Error Pages
    if (customErrorPages) {
      lines.push("# Custom Error Pages");
      if (errorPages.e400) lines.push(`ErrorDocument 400 ${errorPages.e400}`);
      if (errorPages.e403) lines.push(`ErrorDocument 403 ${errorPages.e403}`);
      if (errorPages.e404) lines.push(`ErrorDocument 404 ${errorPages.e404}`);
      if (errorPages.e500) lines.push(`ErrorDocument 500 ${errorPages.e500}`);
      lines.push("");
    }

    // GZIP Compression
    if (gzipCompression) {
      lines.push("# Enable GZIP Compression");
      lines.push("<IfModule mod_deflate.c>");
      lines.push("  AddOutputFilterByType DEFLATE text/html");
      lines.push("  AddOutputFilterByType DEFLATE text/css");
      lines.push("  AddOutputFilterByType DEFLATE text/javascript");
      lines.push("  AddOutputFilterByType DEFLATE text/xml");
      lines.push("  AddOutputFilterByType DEFLATE text/plain");
      lines.push("  AddOutputFilterByType DEFLATE application/javascript");
      lines.push("  AddOutputFilterByType DEFLATE application/x-javascript");
      lines.push("  AddOutputFilterByType DEFLATE application/json");
      lines.push("  AddOutputFilterByType DEFLATE application/xml");
      lines.push("  AddOutputFilterByType DEFLATE application/rss+xml");
      lines.push("  AddOutputFilterByType DEFLATE image/svg+xml");
      lines.push("  AddOutputFilterByType DEFLATE font/ttf");
      lines.push("  AddOutputFilterByType DEFLATE font/otf");
      lines.push("</IfModule>");
      lines.push("");
    }

    // Browser Caching
    if (browserCaching) {
      lines.push("# Browser Caching");
      lines.push("<IfModule mod_expires.c>");
      lines.push("  ExpiresActive On");
      lines.push(`  ExpiresByType image/jpeg \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType image/png \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType image/gif \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType image/webp \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType image/svg+xml \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType image/x-icon \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType text/css \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType text/javascript \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType application/javascript \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType font/ttf \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType font/otf \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType font/woff \"access plus ${cacheExpiry} seconds\"`);
      lines.push(`  ExpiresByType font/woff2 \"access plus ${cacheExpiry} seconds\"`);
      lines.push("</IfModule>");
      lines.push("");
    }

    // Security Headers
    if (securityHeaders) {
      const hasAnyHeader =
        xFrameOptions || xContentTypeOptions || xXssProtection || referrerPolicy || contentSecurityPolicy;
      if (hasAnyHeader) {
        lines.push("# Security Headers");
        lines.push("<IfModule mod_headers.c>");
        if (xFrameOptions) {
          lines.push('  Header always set X-Frame-Options "SAMEORIGIN"');
        }
        if (xContentTypeOptions) {
          lines.push('  Header always set X-Content-Type-Options "nosniff"');
        }
        if (xXssProtection) {
          lines.push('  Header always set X-XSS-Protection "1; mode=block"');
        }
        if (referrerPolicy) {
          lines.push('  Header always set Referrer-Policy "strict-origin-when-cross-origin"');
        }
        if (contentSecurityPolicy) {
          lines.push("  Header always set Content-Security-Policy \"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;\"");
        }
        lines.push("</IfModule>");
        lines.push("");
      }
    }

    // Block Hotlinking
    if (blockHotlinking) {
      lines.push("# Block Hotlinking");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_REFERER} !^$");
      lines.push("RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com [NC]");
      lines.push("RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC,L]");
      lines.push("");
    }

    // Disable Directory Listing
    if (disableDirectoryListing) {
      lines.push("# Disable Directory Listing");
      lines.push("Options -Indexes");
      lines.push("");
    }

    // Custom Redirects
    const validRedirects = redirects.filter((r) => r.source.trim() && r.destination.trim());
    if (validRedirects.length > 0) {
      lines.push("# Custom Redirects");
      lines.push("RewriteEngine On");
      for (const r of validRedirects) {
        lines.push(`Redirect ${r.type} ${r.source} ${r.destination}`);
      }
      lines.push("");
    }

    return lines.join("\n").trimEnd();
  }, [
    forceHttps,
    wwwOption,
    customErrorPages,
    errorPages,
    gzipCompression,
    browserCaching,
    cacheExpiry,
    securityHeaders,
    xFrameOptions,
    xContentTypeOptions,
    xXssProtection,
    referrerPolicy,
    contentSecurityPolicy,
    blockHotlinking,
    disableDirectoryListing,
    redirects,
  ]);

  return (
    <ToolLayout
      title=".htaccess Generator"
      description="Generate .htaccess rules for Apache servers. Configure redirects, HTTPS, caching, compression, security headers, and more."
      relatedTools={["robots-txt-generator", "meta-tag-generator", "url-parser"]}
    >
      <div className="space-y-6">
        {/* Force HTTPS */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={forceHttps}
              onChange={(e) => setForceHttps(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Force HTTPS
          </label>
          <p className="ml-6 mt-0.5 text-xs text-gray-500 dark:text-gray-400">
            Redirect all HTTP traffic to HTTPS
          </p>
        </div>

        {/* WWW Handling */}
        <div>
          <span className="block text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
            WWW Handling
          </span>
          <div className="flex flex-wrap gap-4 ml-1">
            {[
              { value: "none" as const, label: "No change" },
              { value: "force" as const, label: "Force WWW" },
              { value: "remove" as const, label: "Remove WWW" },
            ].map((opt) => (
              <label
                key={opt.value}
                className="flex items-center gap-1.5 text-sm text-gray-600 dark:text-gray-400"
              >
                <input
                  type="radio"
                  name="www"
                  value={opt.value}
                  checked={wwwOption === opt.value}
                  onChange={() => setWwwOption(opt.value)}
                  className="border-gray-300 dark:border-gray-600"
                />
                {opt.label}
              </label>
            ))}
          </div>
        </div>

        {/* Custom Error Pages */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={customErrorPages}
              onChange={(e) => setCustomErrorPages(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Custom Error Pages
          </label>
          {customErrorPages && (
            <div className="ml-6 mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
              {[
                { code: "400", key: "e400" as const, label: "400 Bad Request" },
                { code: "403", key: "e403" as const, label: "403 Forbidden" },
                { code: "404", key: "e404" as const, label: "404 Not Found" },
                { code: "500", key: "e500" as const, label: "500 Server Error" },
              ].map((err) => (
                <div key={err.code}>
                  <label className="mb-1 block text-xs text-gray-600 dark:text-gray-400">
                    {err.label}
                  </label>
                  <input
                    type="text"
                    value={errorPages[err.key]}
                    onChange={(e) =>
                      setErrorPages((prev) => ({
                        ...prev,
                        [err.key]: e.target.value,
                      }))
                    }
                    placeholder={`/error-${err.code}.html`}
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none"
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        {/* GZIP Compression */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={gzipCompression}
              onChange={(e) => setGzipCompression(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Enable GZIP Compression
          </label>
          <p className="ml-6 mt-0.5 text-xs text-gray-500 dark:text-gray-400">
            Compress text, CSS, JavaScript, XML, and font files
          </p>
        </div>

        {/* Browser Caching */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={browserCaching}
              onChange={(e) => setBrowserCaching(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Browser Caching
          </label>
          {browserCaching && (
            <div className="ml-6 mt-3">
              <label className="mb-1 block text-xs text-gray-600 dark:text-gray-400">
                Cache Expiry Time
              </label>
              <select
                value={cacheExpiry}
                onChange={(e) => setCacheExpiry(e.target.value)}
                className="rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none"
              >
                {CACHE_EXPIRY_OPTIONS.map((opt) => (
                  <option key={opt.value} value={opt.value}>
                    {opt.label}
                  </option>
                ))}
              </select>
            </div>
          )}
        </div>

        {/* Security Headers */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={securityHeaders}
              onChange={(e) => setSecurityHeaders(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Security Headers
          </label>
          {securityHeaders && (
            <div className="ml-6 mt-3 space-y-2">
              {[
                { checked: xFrameOptions, set: setXFrameOptions, label: "X-Frame-Options (SAMEORIGIN)" },
                { checked: xContentTypeOptions, set: setXContentTypeOptions, label: "X-Content-Type-Options (nosniff)" },
                { checked: xXssProtection, set: setXXssProtection, label: "X-XSS-Protection (1; mode=block)" },
                { checked: referrerPolicy, set: setReferrerPolicy, label: "Referrer-Policy (strict-origin-when-cross-origin)" },
                { checked: contentSecurityPolicy, set: setContentSecurityPolicy, label: "Content-Security-Policy (default)" },
              ].map((header) => (
                <label
                  key={header.label}
                  className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400"
                >
                  <input
                    type="checkbox"
                    checked={header.checked}
                    onChange={(e) => header.set(e.target.checked)}
                    className="rounded border-gray-300 dark:border-gray-600"
                  />
                  {header.label}
                </label>
              ))}
            </div>
          )}
        </div>

        {/* Block Hotlinking */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={blockHotlinking}
              onChange={(e) => setBlockHotlinking(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Block Hotlinking
          </label>
          <p className="ml-6 mt-0.5 text-xs text-gray-500 dark:text-gray-400">
            Prevent other sites from embedding your images (update &quot;yourdomain.com&quot; in the output)
          </p>
        </div>

        {/* Disable Directory Listing */}
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-gray-100">
            <input
              type="checkbox"
              checked={disableDirectoryListing}
              onChange={(e) => setDisableDirectoryListing(e.target.checked)}
              className="rounded border-gray-300 dark:border-gray-600"
            />
            Disable Directory Listing
          </label>
          <p className="ml-6 mt-0.5 text-xs text-gray-500 dark:text-gray-400">
            Prevent Apache from showing a list of files in directories
          </p>
        </div>

        {/* Custom Redirects */}
        <div>
          <div className="mb-3 flex items-center justify-between">
            <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
              Custom Redirects
            </span>
            <button
              onClick={addRedirect}
              className="rounded-lg bg-blue-600 px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-blue-700"
            >
              + Add Redirect
            </button>
          </div>
          {redirects.length === 0 && (
            <p className="text-sm text-gray-400 dark:text-gray-500">
              No custom redirects added yet. Click &quot;+ Add Redirect&quot; to begin.
            </p>
          )}
          <div className="space-y-3">
            {redirects.map((r) => (
              <div
                key={r.id}
                className="flex flex-wrap items-end gap-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-950 p-3"
              >
                <div className="flex-1 min-w-[140px]">
                  <label className="mb-1 block text-xs text-gray-600 dark:text-gray-400">
                    Source Path
                  </label>
                  <input
                    type="text"
                    value={r.source}
                    onChange={(e) => updateRedirect(r.id, "source", e.target.value)}
                    placeholder="/old-page"
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none"
                  />
                </div>
                <div className="flex-1 min-w-[180px]">
                  <label className="mb-1 block text-xs text-gray-600 dark:text-gray-400">
                    Destination URL
                  </label>
                  <input
                    type="text"
                    value={r.destination}
                    onChange={(e) =>
                      updateRedirect(r.id, "destination", e.target.value)
                    }
                    placeholder="https://example.com/new-page"
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none"
                  />
                </div>
                <div className="w-24">
                  <label className="mb-1 block text-xs text-gray-600 dark:text-gray-400">
                    Type
                  </label>
                  <select
                    value={r.type}
                    onChange={(e) =>
                      updateRedirect(r.id, "type", e.target.value)
                    }
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm focus:border-blue-500 dark:border-blue-400 focus:outline-none"
                  >
                    <option value="301">301</option>
                    <option value="302">302</option>
                  </select>
                </div>
                <button
                  onClick={() => removeRedirect(r.id)}
                  className="rounded-lg border border-red-200 dark:border-red-800 bg-white dark:bg-gray-900 px-3 py-2 text-sm text-red-600 dark:text-red-400 transition-colors hover:bg-red-50 dark:bg-red-950 dark:hover:bg-red-950"
                >
                  Remove
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Generated Output */}
        <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
          <div className="mb-2 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-gray-100">
              Generated .htaccess
            </h3>
            <CopyButton text={htaccessContent} />
          </div>
          <pre className="overflow-x-auto rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-950 p-4 text-sm leading-relaxed">
            <code>{htaccessContent || "# Select options above to generate .htaccess rules"}</code>
          </pre>
        </div>
      </div>

      
      {/* SEO Content */}
      <div className="mt-12 space-y-6 text-gray-600 dark:text-gray-400 text-sm leading-relaxed border-t border-gray-200 dark:border-gray-700 pt-8">
        <h2 className="text-xl font-bold text-gray-800 dark:text-gray-200">
          About This Tool
        </h2>
        <p>
          The .htaccess Generator is a free online tool available on CodeUtilo. Generate .htaccess rules for redirects, HTTPS, caching, and security headers. All processing happens directly in your browser — no data is ever sent to any server, ensuring your privacy and security. No signup or installation is required.
        </p>

        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          Key Features
        </h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Browser-Based Processing</strong> — All .htaccess generator operations run locally in your browser using JavaScript. Your data never leaves your device.
          </li>
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Instant Results</strong> — Get results immediately as you type or paste your input. No waiting for server responses or page reloads.
          </li>
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Free &amp; No Signup</strong> — Use the .htaccess generator as many times as you need without creating an account or paying anything.
          </li>
          <li>
            <strong className="text-gray-700 dark:text-gray-300">Mobile Friendly</strong> — Works on desktop, tablet, and mobile browsers. Access this tool from any device with an internet connection.
          </li>
        </ul>

        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          Common Use Cases
        </h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Using the .htaccess generator for day-to-day development tasks</li>
          <li>Saving time on repetitive tasks by using a browser-based tool instead of writing custom code</li>
          <li>Working on projects where installing software is not an option (school, work, shared computers)</li>
          <li>Quick prototyping and debugging without switching to a terminal or IDE</li>
          <li>Sharing the tool link with colleagues who need the same functionality</li>
        </ul>

        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          How to Use
        </h2>
        <p>
          Enter your input in the text area provided and the .htaccess generator will process it instantly. Use the Copy button to copy the result to your clipboard. All operations are performed locally in your browser — no data is transmitted to any server.
        </p>
      
        <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200">
          Frequently Asked Questions
        </h2>
        <div className="space-y-4">
          <details className="group">
            <summary className="cursor-pointer font-medium text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400">
              Is the .htaccess Generator free to use?
            </summary>
            <p className="mt-2 pl-4 text-gray-600 dark:text-gray-400">
              Yes, the .htaccess Generator is completely free with no usage limits. There is no signup or registration required. You can use it as many times as you need.
            </p>
          </details>
          <details className="group">
            <summary className="cursor-pointer font-medium text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400">
              Is my data safe when using this tool?
            </summary>
            <p className="mt-2 pl-4 text-gray-600 dark:text-gray-400">
              Yes. All processing happens locally in your browser using JavaScript. Your data is never uploaded to any server or stored anywhere. Everything stays on your device.
            </p>
          </details>
          <details className="group">
            <summary className="cursor-pointer font-medium text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400">
              Does this tool work on mobile devices?
            </summary>
            <p className="mt-2 pl-4 text-gray-600 dark:text-gray-400">
              Yes. The .htaccess Generator is fully responsive and works on smartphones, tablets, and desktop computers. You can use it from any modern browser on any device.
            </p>
          </details>
          <details className="group">
            <summary className="cursor-pointer font-medium text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400">
              Do I need to install anything?
            </summary>
            <p className="mt-2 pl-4 text-gray-600 dark:text-gray-400">
              No. The .htaccess Generator runs entirely in your web browser. There is nothing to download or install. Just open the page and start using it immediately.
            </p>
          </details>
        </div>
</div>
    </ToolLayout>
  );
}
