import type { Metadata } from "next";
import FAQSchema from "@/components/FAQSchema";
import SchemaOrg from "@/components/SchemaOrg";

export const metadata: Metadata = {
  title: "QR Code Generator Online — Free QR Code Maker",
  description: "Generate QR codes from text or URLs instantly. Customize size and colors. Download as PNG or SVG. Free online QR code generator.",
  keywords: ["qr code generator","qr code maker","qr code online","generate qr code","free qr code"],
  openGraph: {
    title: "QR Code Generator Online — Free QR Code Maker | CodeUtilo",
    description: "Generate QR codes from text or URLs instantly. Customize size and colors. Download as PNG or SVG. Free online QR code generator.",
    url: "https://codeutilo.com/qr-code-generator",
    siteName: "CodeUtilo",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "QR Code Generator Online — Free QR Code Maker | CodeUtilo",
    description: "Generate QR codes from text or URLs instantly. Customize size and colors. Download as PNG or SVG. Free online QR code generator.",
  },
  alternates: {
    canonical: "https://codeutilo.com/qr-code-generator",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <SchemaOrg
        name="Qr Code Generator"
        description="Generate QR codes from text or URLs instantly. Customize size and colors. Download as PNG or SVG. Free online QR code generator."
        slug="qr-code-generator"
      />
        <FAQSchema faqs={[{"question":"What can I put in a QR code?","answer":"QR codes can encode URLs, plain text, email addresses, phone numbers, Wi-Fi network credentials, vCards (contact info), calendar events, and more. The most common use is encoding website URLs."},{"question":"What is the maximum data capacity of a QR code?","answer":"A QR code can hold up to 4,296 alphanumeric characters or 7,089 numeric characters. However, more data means a denser QR code that's harder to scan. Keep content short for best scanning reliability."},{"question":"Can I customize the colors of a QR code?","answer":"Yes. This tool lets you customize the foreground and background colors. However, ensure high contrast between foreground and background for reliable scanning. Dark foreground on light background works best."},{"question":"Do QR codes expire?","answer":"Static QR codes (like those generated by this tool) never expire — they encode data directly. Dynamic QR codes (offered by paid services) point to a redirect URL that can be changed or disabled."}]} />
      {children}
    </>
  );
}
